server:
  port: 5000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-gateway-5000  # 修改默认的描述信息

# actuator/info 配置
info:
  app.name: springcloud-gateway
  company.name: hao.blog