
spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-consumer-8080  # 修改默认的描述信息

# actuator/info 配置
info:
  app.name: springcloud-consumer-dept
  company.name: hao.blog