
spring:
  application:
    name: consumer
  zipkin: # sleuth + zipkin 配置
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: consumer
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-consumer-8080  # 修改默认的描述信息

# actuator/info 配置
info:
  app.name: springcloud-consumer-dept
  company.name: hao.blog