
spring:
  application:
    name: consumerFeign
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8001  # 配置 sentinel dashboard 页面
  zipkin: # sleuth + zipkin 配置
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: consumerFeign
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-consumerFeign-8080  # 修改默认的描述信息

# actuator/info 配置
info:
  app.name: springcloud-consumerFeign-dept
  company.name: hao.blog

# 开启 sentinel
feign:
  sentinel:
    enabled: true