server:
  port: 8081

mybatis:
  type-aliases-package: com.zhao.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis-config.xml

spring:
  application:
    name: provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678