server:
  port: 8082

# Mybatis 配置
mybatis:
  type-aliases-package: com.zhao.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis-config.xml

# Spring 配置
spring:
  application:
    name: provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud02?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
  zipkin: # sleuth + zipkin 配置
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: provider2
  sleuth:
    sampler:
      probability: 1

# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-provider-8082  # 修改默认的描述信息


# actuator/info 配置
info:
  app.name: springcloud-provider-dept
  company.name: hao.blog


